### ISSUE TITLE
Error in EJAngular2Module is not an NgModule

### ISSUE THREAD

**Issue by GasyTek** [syncfusion/ej-angular2#1]
Hi,

I use Angular CLI (version 1.0.1) and EJ-Angular (version 15.1.44).
I get the error message metionned on the title when I run my Angular 2 app with the command "ng serve".
What is strange is that it disappears when the app is "live recompiled" ..

Any ideas ? Thanks

Riana

**Comment by karthickthangasamy** [comment]
Hi @GasyTek ,

That is because issue in Angular CLI, refer to the thread [here](https://github.com/angular/angular-cli/issues/4594) to explore.

To resolve the issue, we can import the **EJAngular2Module** like the below code snippet.

```
import { EJAngular2Module } from 'ej-angular2';  
 
const EJModule: ModuleWithProviders = { 
    ngModule: EJAngular2Module 
}; 
 
 
@NgModule({ 
  declarations: [ 
    AppComponent 
  ], 
  imports: [ 
    BrowserModule, 
    FormsModule, 
    HttpModule, 
    EJModule 
  ], 
  providers: [], 
  bootstrap: [AppComponent] 
}) 

```

Hope the information helps.!!!

**Comment by susandotmark** [comment]
> Hi @GasyTek ,
> 
> That is because issue in Angular CLI, refer to the thread [here](https://github.com/angular/angular-cli/issues/4594) to explore.
> 
> To resolve the issue, we can import the **EJAngular2Module** like the below code snippet.
> 
> ```
> import { EJAngular2Module } from 'ej-angular2';  
>  
> const EJModule: ModuleWithProviders = { 
>     ngModule: EJAngular2Module 
> }; 
>  
>  
> @NgModule({ 
>   declarations: [ 
>     AppComponent 
>   ], 
>   imports: [ 
>     BrowserModule, 
>     FormsModule, 
>     HttpModule, 
>     EJModule 
>   ], 
>   providers: [], 
>   bootstrap: [AppComponent] 
> }) 
> ```
> Hope the information helps.!!!

still throws error

**Comment by AbinayaSubbiah** [comment]
Hi GasyTek,

The previously reported issue due to old version of our Syncfusion Angular component package ej-angular2(15.1.44) not supports in-built AOT compilation with [Angular CLI](https://cli.angular.io/) (version 1.0.1) which have internally AOT compilation by default. Since we provided the work around solution to resolve the issue. Now the latest version of Syncfusion Angular components supports AOT Compilation so we suggest you to try the below one of the solution.

-	Upgrade Angular CLI and Syncfusion Angular dependencies to latest.
`npm install @angular/cli@latest -g `
`npm install syncfusion-javascript --save`
`npm install ej-angular2 –save`
`npm install --save-dev @types/jquery`
`npm install --save-dev @types/ej.web.all`

- If you are using Angular CLI version 1.0.1 upgrade Syncfusion Angular components with below list of command.
`npm install syncfusion-javascript --save`
`npm install ej-angular2 –save`
`npm install --save-dev @types/jquery@2.0`
`npm install --save-dev @types/ej.web.all`

Please let us know if you need further assistance on this.
